# Generated by Django 5.0.7 on 2024-07-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0002_alter_books_about_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
