# Generated by Django 5.0.7 on 2024-07-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0003_rename_books_book_rename_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile_images/'),
        ),
    ]
